application.title=FileServer
application.formatted-version=${APPLICATION_VERSION:(v1.0.0)}

spring.application.name=video-viewer

home.dir=D:/FileServer
resources.dir=A:/Desktop/My Projects/Spring-FileService/src/main/resources/static

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# DB configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/file-server
spring.datasource.username=root
spring.datasource.password=password

# FlyWay configuration
spring.flyway.locations=classpath:db/migrations
spring.flyway.user=${spring.datasource.username}
spring.flyway.url=${spring.datasource.url}
spring.flyway.password=${spring.datasource.password}
spring.flyway.schemas=public

# AUTH
## CORS
application.cors.urls=${FRONTEND_URL:http://localhost:4200, http://192.168.1.2:4200, http://192.168.1.5:4200, http://93.116.234.164:4200}
application.cors.methods=*
application.cors.headers=*

## JWT
application.secrets.access=V1RJNVJtVnVXWHBsYmtreFpXcGFlbU5IVWtsT1ZscFhZekZOUFE9PQ==
application.secrets.refresh=WVZad2IyRnNRbGxTTVZKUFZraHdZV1F3ZHpCV1NIQnRWa1JKUFE9PQ==
application.secrets.streaming=VWtWSmVGSnJlRGxoVm5CRVducFZNVkpzTVVKVmJIQk9XVEpPWWxWRVVteGhla3B4V21veGRBPT0=

## PASSWORD RESET
application.password-reset.url=http://192.168.1.2:4200/reset-password

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${FILE_SERVER_MAILER_EMAIL}
spring.mail.password=${FILE_SERVER_MAILER_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true