application.title=FileServer
application.formatted-version=${APPLICATION_VERSION:(v1.0.0)}

spring.application.name=video-viewer

home.dir=B:/Courses
resources.dir=A:/Desktop/old - before 25.04.25/old before the 14.03.25/Spring-WEBFlux/src/main/resources/static

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB